### ISSUE TITLE
Custom JavaScript for Websites Init Twice Issue

### ISSUE THREAD

**Issue by xcv58** [xcv58/Custom-JavaScript-for-Websites-2#180]
> Thanks you in advanced for creating an excellent tool.

> Not sure is the chrome version updated or something else. I encountered an issue recently.
> The issue is the javascript will be injected twice currently.
> I have reset all the rule and try to do some code tracing.
> Not lucky with finding some useful information. With my little knowledge in chrome extension. Is there a possibility with the post message ?
> If you need further information please let me know. 
> Thanks again and hope this is a issue worth to fix.

**Comment by xcv58** [comment]
I couldn't reproduce this on Chrome Version 88.0.4324.11:
![image](https://user-images.githubusercontent.com/503123/100650847-6a80bf00-32f9-11eb-8dcb-8cc0a32a5d0f.png)

**Comment by Darrellwan** [comment]
I found the root cause and apologize for it's not issue from the extension .
After I tried to console the document title and location href in the extension. It returned two different title, one of them is saleforce toolkit in dev environment. 
<img width="365" alt="2020-12-01 10_29_46-Clipboard" src="https://user-images.githubusercontent.com/6909524/100689903-5bb10f80-33c0-11eb-90bd-837fd0f9d147.png">
I have to mask some of the picture since it's not my website.

If anyone encountered the same issue in the future. You can check if there is some request in the network that match the same domain or regular expression 

Thanks again for creating the ticket.

**Comment by xcv58** [comment]
Cool, thank you for the follow-up @Darrellwan
