### ISSUE TITLE
Recently stopped working.

### ISSUE THREAD

**Issue by xul8tr** [xcv58/Custom-JavaScript-for-Websites-2#55]
Tried with current version and dev. The popup just shows a spinning blue circle and when i inspect it complains about 

    Array.from(o, function() {
            throw 2
        })

popup.js:63 Uncaught (in promise) Error: Get no data for active tab!
    at popup.js:63
    at Generator.next (<anonymous>)
    at r (popup.js:63)
    at popup.js:63
    at new Promise (<anonymous>)
    at popup.js:63
    at popup.js:63
    at e (popup.js:51)
(anonymous) @ popup.js:63
r @ popup.js:63
(anonymous) @ popup.js:63
(anonymous) @ popup.js:63
(anonymous) @ popup.js:63
e @ popup.js:51
popup.js:51 Uncaught (in promise) Error: The message port closed before a response was received.
    at e (popup.js:51)

**Comment by xcv58** [comment]
Thanks @xul8tr 
Does this happen for all tabs or just some tabs?

**Comment by xul8tr** [comment]
All, i tried on 2 different computers

**Comment by xcv58** [comment]
The message `The message port closed before a response was received` should appear in development mode only. Are you trying to dev this extension?

I can't reproduce the same bug on my laptop. Could you please provide your operating system and chrome version?

**Comment by xcv58** [comment]
I can only reproduce your bug once on Chrome Dev. Does it work without `Inspect Popup`?

If yes, you can open it in a new tab and inspect the normal tab.

**Comment by xul8tr** [comment]
No, it just sits and spins, 2.5.1 works.

**Comment by xcv58** [comment]
Do you mean the (2.5.1)[https://github.com/xcv58/Custom-JavaScript-for-Websites-2/releases/tag/v2.5.1]?

Could you please try 3.0.0?

**Comment by xul8tr** [comment]
I went from latest tag to the next, one by one. It wasn't until 2.5.1 that it worked in developer mode.

**Comment by xcv58** [comment]
Tried several possible ways to reproduce the bug. All below can't reproduce the bug:

- Use `npm` instead of `yarn`
- Use lower version node
- Use different versions of Chrome

It seems the bug occurs during the connection between the extension and background page:
https://github.com/xcv58/Custom-JavaScript-for-Websites-2/blob/fb9ae5924426ad84721de916572832489682384a/src/js/stores/AppStore.js#L102

It would be helpful if you can log the response and call in both `AppStore` and [`background.js`](https://github.com/xcv58/Custom-JavaScript-for-Websites-2/blob/fb9ae5924426ad84721de916572832489682384a/src/js/background.js#L9). Since I can't reproduce the bug.
